INSERT INTO manufacturer (name) VALUES ('Samsung');    -- 1
INSERT INTO manufacturer (name) VALUES ('Dell');       -- 2
INSERT INTO manufacturer (name) VALUES ('HP');         -- 3
INSERT INTO manufacturer (name) VALUES ('Apple');      -- 4
INSERT INTO manufacturer (name) VALUES ('Lenovo');     -- 5
INSERT INTO manufacturer (name) VALUES ('Acer');       -- 6
INSERT INTO manufacturer (name) VALUES ('AMD');        -- 7
INSERT INTO manufacturer (name) VALUES ('LG');         -- 8
INSERT INTO manufacturer (name) VALUES ('Bosch');      -- 9
INSERT INTO manufacturer (name) VALUES ('Philips');    -- 10
INSERT INTO manufacturer (name) VALUES ('Sony');       -- 11
INSERT INTO manufacturer (name) VALUES ('Panasonic');  -- 12
INSERT INTO manufacturer (name) VALUES ('Siemens');    -- 13
INSERT INTO manufacturer (name) VALUES ('Whirlpool');  -- 14
INSERT INTO manufacturer (name) VALUES ('Electrolux'); -- 15
INSERT INTO manufacturer (name) VALUES ('Miele');      -- 16
INSERT INTO manufacturer (name) VALUES ('Dyson');      -- 17
INSERT INTO manufacturer (name) VALUES ('Haier');      -- 18
INSERT INTO manufacturer (name) VALUES ('Beko');       -- 19
INSERT INTO manufacturer (name) VALUES ('Indesit');    -- 20
INSERT INTO manufacturer (name) VALUES ('Gorenje');    -- 21
