-- Manufacturers
INSERT INTO manufacturer (name) VALUES ('Samsung');
INSERT INTO manufacturer (name) VALUES ('Dell');
INSERT INTO manufacturer (name) VALUES ('HP');
INSERT INTO manufacturer (name) VALUES ('Apple');
INSERT INTO manufacturer (name) VALUES ('Lenovo');
INSERT INTO manufacturer (name) VALUES ('Acer');
INSERT INTO manufacturer (name) VALUES ('AMD');
INSERT INTO manufacturer (name) VALUES ('LG');
INSERT INTO manufacturer (name) VALUES ('Bosch');
INSERT INTO manufacturer (name) VALUES ('Philips');
INSERT INTO manufacturer (name) VALUES ('Sony');
INSERT INTO manufacturer (name) VALUES ('Panasonic');
INSERT INTO manufacturer (name) VALUES ('Siemens');
INSERT INTO manufacturer (name) VALUES ('Whirlpool');
INSERT INTO manufacturer (name) VALUES ('Electrolux');
INSERT INTO manufacturer (name) VALUES ('Miele');
INSERT INTO manufacturer (name) VALUES ('Dyson');
INSERT INTO manufacturer (name) VALUES ('Haier');
INSERT INTO manufacturer (name) VALUES ('Beko');
INSERT INTO manufacturer (name) VALUES ('Indesit');
INSERT INTO manufacturer (name) VALUES ('Gorenje');

-- Employees (passwords: Name@123!)
INSERT INTO employee (name, email, password, department) VALUES
    ('Phobos',  'phobos@gmail.com',  '$2a$10$y6jt2UCgNttEEyVvfnIHYOOGVAFqcgleYk97HCRIHF3oJpc/T/DDW', 'salle'),
    ('Moon',    'moon@gmail.com',    '$2a$10$wDvPzfrpYeqpdEP.sos9UuW3dzB5lD8MII6iYjvCsyzLPPjkdwJKq', 'salle'),
    ('Deimos',  'deimos@gmail.com',  '$2a$10$nI5BrzPrcZf4zi5WEyqI4.8GrlCiHJXsYQL2OaWbpuy7GHnjmKEBm', 'security'),
    ('Europa',  'europa@gmail.com',  '$2a$10$3KrmGHDqxfPS3hthFOpZO.mkED31AL5bYmMRyvaC0MHyPwQIiWHK6', 'security');

-- Clients (passwords: Name@123!)
INSERT INTO client (name, email, password, card) VALUES ('Mercury', 'mercury@gmail.com', '$2a$10$XHMqqIePHWwieskWz4GXce2FSJT4fAhuxSZnx04TaWi1LVn8H4zvK', '5326-1111');
INSERT INTO client (name, email, password, card) VALUES ('Venus',   'venus@gmail.com',   '$2a$10$5E3LGuuKPUAr6gl2W8V8werPjCIBnuSpJ2mOmNZ184lQRh9vEMtH2', '5326-2222');
INSERT INTO client (name, email, password, card) VALUES ('Earth',   'earth@gmail.com',   '$2a$10$HMudRJKfC/sis1PXwDDF7.xNnjU.M64HuBUTJQFoNLgDLowrdi0N6', '5326-3333');
INSERT INTO client (name, email, password, card) VALUES ('Mars',    'IamGod@gmail.com',  '$2a$10$ql7RgvaPy7iZLkD4Z3jNruNmsdQ6e03hsl0yOMJFki49QzopcEunO', '5326-4444');
INSERT INTO client (name, email, password, card) VALUES ('Jupiter', 'jupiter@gmail.com', '$2a$10$E.wukijJiXK/Dl6/Yn9zmOeBKVGG/Ob1h64GLV47m9f9gYR/1WGCG', '5326-5555');
INSERT INTO client (name, email, password, card) VALUES ('Saturn',  'saturn@gmail.com',  '$2a$10$CEL.ncX1F0Ytz/iWBBlUj.GnuJ1TyuzkRAueUTArphKtFIMLgA81i', '5326-6666');
INSERT INTO client (name, email, password, card) VALUES ('Uranus',  'uranus@gmail.com',  '$2a$10$j73Sm8L.pBzv0Bdig7ASaOsNr0t/EqlROi12hR43pPkspVf/Vo8fC', '5326-7777');
INSERT INTO client (name, email, password, card) VALUES ('Neptune', 'neptune@gmail.com', '$2a$10$ruYETJZRX9c9fD1uPskPnOXCyZReNlkzqjHgro4MOD.uh25BIsgNC', '5326-8888');

-- Appliances
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Claw', 'BIG', '-----', 1, 'ACCUMULATOR', '-------', '-----', 600, 1.01);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Bane', 'SMALL', '-----', 3, 'AC110', '--------', '-----', 2200, 2.01);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Ecu', 'SMALL', '-----', 2, 'ACCUMULATOR', '--------', '-----', 800, 3.01);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Kang Dae', 'BIG', '-----', 4, 'AC220', '--------', '-----', 3600, 4.01);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Gust', 'BIG', '-----', 5, 'ACCUMULATOR', '--------', '-----', 650, 5.01);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Ancile', 'SMALL', '-----', 6, 'AC220', '--------', '-----', 230, 6.01);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Halo', 'BIG', '-----', 7, 'ACCUMULATOR', '--------', '-----', 300, 7.01);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Side-by-Side Refrigerator', 'BIG', 'RS68A8820S9', 1, 'AC220', 'A++, 634L, No Frost', 'Large side-by-side fridge with ice maker and water dispenser', 350, 1299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('French Door Refrigerator', 'BIG', 'GBB92STAXP', 8, 'AC220', 'A+++, 509L, No Frost', 'Premium french door refrigerator with Total No Frost', 195, 1099.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Freestanding Refrigerator', 'BIG', 'KAN93VIFP', 9, 'AC220', 'A++, 508L, NoFrost', 'Bosch French door fridge with VitaFresh technology', 375, 1199.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Bottom Freezer Fridge', 'BIG', 'RB38A7B5E22', 1, 'AC220', 'A++, 385L, SpaceMax', 'Samsung bottom freezer with All-Around Cooling', 200, 749.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Top Freezer Refrigerator', 'BIG', 'GBM17L7XEU', 8, 'AC220', 'A+, 264L, Total No Frost', 'LG top freezer with smart diagnosis', 170, 499.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Compact Refrigerator', 'BIG', 'GTS18HYNRFS', 18, 'AC220', 'A+, 182L', 'Haier compact two-door refrigerator', 100, 279.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Retro Fridge', 'BIG', 'CS50DSBHE', 21, 'AC220', 'A++, 298L, No Frost', 'Gorenje retro-style refrigerator with dispenser', 185, 649.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Multi-Door Fridge', 'BIG', 'RF23BB8200AP', 1, 'AC220', 'A++, 635L, Bespoke', 'Samsung Bespoke multi-door with customisable panels', 405, 1599.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Built-in Refrigerator', 'BIG', 'KI87SADD0', 13, 'AC220', 'A++, 319L, flatHinge', 'Siemens built-in fridge-freezer combination', 230, 1049.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Inox Refrigerator', 'BIG', 'EN3854MOX', 15, 'AC220', 'A++, 371L, No Frost', 'Electrolux stainless steel fridge with TasteGuard', 210, 829.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Front Load Washer', 'BIG', 'WW90T554DAT', 1, 'AC220', 'A+++, 9kg, 1400rpm', 'Samsung AddWash with steam and AI control', 2000, 699.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Front Load Washer', 'BIG', 'F4WV509S1E', 8, 'AC220', 'A+++, 9kg, 1400rpm', 'LG AI Direct Drive with steam technology', 1900, 749.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Washer Dryer Combo', 'BIG', 'WD4HG2B23SN', 9, 'AC220', 'A, 9/6kg, 1400rpm', 'Bosch Series 6 washer-dryer with AutoDry', 2200, 1099.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Front Load Washer', 'BIG', 'WM14N075NL', 13, 'AC220', 'A+++, 7kg, 1400rpm', 'Siemens iQ300 with iQdrive motor', 1800, 549.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Top Load Washer', 'BIG', 'WTW5000DW', 14, 'AC220', 'A+, 8kg, 900rpm', 'Whirlpool top loader with 6th Sense technology', 1800, 429.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Slim Washing Machine', 'BIG', 'EW6S226SI', 15, 'AC220', 'A+++, 6kg, 1200rpm', 'Electrolux slim front loader for small spaces', 1400, 399.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Freestanding Washer', 'BIG', 'WDB 030 WCS EU', 16, 'AC220', 'A+++, 6kg, 1400rpm', 'Miele W1 with TwinDos automatic detergent', 1900, 1299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Front Load Washer', 'BIG', 'BFL7221V', 19, 'AC220', 'A+++, 7kg, 1200rpm', 'Beko front loader with AquaTech technology', 1600, 369.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Front Load Washer', 'BIG', 'BWSE71283', 20, 'AC220', 'A++, 7kg, 1200rpm', 'Indesit washer with Push&Wash function', 1400, 299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Freestanding Dishwasher', 'BIG', 'SMS4HCB48E', 9, 'AC220', 'A++, 14 place settings', 'Bosch Serie 4 with VarioDrawer and EfficientDry', 2400, 649.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Built-in Dishwasher', 'BIG', 'DW60M6070IB', 1, 'AC220', 'A+++, 14 place settings', 'Samsung built-in dishwasher with Zone Booster', 1800, 599.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Freestanding Dishwasher', 'BIG', 'GSX961FDI', 16, 'AC220', 'A+++, 14 place settings', 'Miele G 7000 with AutoDos and PowerDisk', 2100, 1399.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Slim Dishwasher', 'BIG', 'SN25ZI49CE', 13, 'AC220', 'A++, 10 place settings, 45cm', 'Siemens slim dishwasher with zeolite drying', 1800, 749.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Freestanding Dishwasher', 'BIG', 'ESF5513LOX', 15, 'AC220', 'A++, 13 place settings', 'Electrolux 700 series with AirDry technology', 2000, 499.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Countertop Dishwasher', 'BIG', 'DTC62', 18, 'AC220', 'A++, 6 place settings', 'Haier compact countertop dishwasher', 1150, 349.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Freestanding Dishwasher', 'BIG', 'DFIN 11310', 20, 'AC220', 'A++, 15 place settings', 'Indesit dishwasher with Eco function', 1950, 349.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Electric Oven', 'BIG', 'NV75N5571RS', 1, 'AC220', 'A+, 75L, Dual Cook', 'Samsung dual cook flex oven with steam', 3600, 699.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Pyrolytic Oven', 'BIG', 'HBA578BS1', 9, 'AC220', 'A+, 71L, Pyrolysis', 'Bosch Serie 6 pyrolytic oven with EcoClean', 3600, 799.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Steam Oven', 'BIG', 'DG 6401', 16, 'AC220', 'A, 40L, Steam', 'Miele steam oven with PerfectClean enamel', 1800, 1599.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Electric Range', 'BIG', 'NE63T8751SS', 1, 'AC220', 'A, 5 burners, 30L', 'Samsung flex duo range with Air Fry', 12500, 1099.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Built-in Oven', 'BIG', 'HB636GHS1', 13, 'AC220', 'A+, 66L, ecoClean', 'Siemens iQ700 oven with activeClean', 3600, 899.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Electric Oven', 'BIG', 'EOC6851AAX', 15, 'AC220', 'A+, 72L, SteamBake', 'Electrolux multifunction oven with SteamBake', 3500, 649.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Split Air Conditioner', 'BIG', 'AR12TXHQBWKXEU', 1, 'AC220', 'A+++/A++, 12000 BTU, Inverter', 'Samsung WindFree inverter AC with Wi-Fi', 1250, 799.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Split Air Conditioner', 'BIG', 'S12ET.NSJ', 8, 'AC220', 'A++/A+, 12000 BTU, Dual Inverter', 'LG Dual Inverter with 10-year compressor warranty', 1200, 749.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Portable Air Conditioner', 'BIG', 'PAC M14-KIT', 12, 'AC220', 'A, 14000 BTU', 'Panasonic portable AC with heat pump', 1450, 649.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Split Air Conditioner', 'BIG', 'G12EK-PR1-I', 21, 'AC220', 'A+++/A++, 12000 BTU', 'Gorenje split inverter AC with triple filter', 1100, 699.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Wall-Mounted AC', 'BIG', 'MSZ-HR35VF', 12, 'AC220', 'A++/A+, 12000 BTU, Inverter', 'Mitsubishi inverter with plasma quad filter', 1230, 899.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('4K QLED TV', 'BIG', 'QE55Q80CATXXH', 1, 'AC220', '4K, 55", QLED, Smart TV', 'Samsung QLED with Quantum HDR 1500', 130, 999.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('OLED TV', 'BIG', 'OLED55C34LA', 8, 'AC220', '4K, 55", OLED, WebOS', 'LG C3 OLED with a9 Gen6 AI Processor', 120, 1299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('4K TV', 'BIG', 'KD-55X85K', 11, 'AC220', '4K, 55", IPS, Google TV', 'Sony Bravia X85K with XR processor', 115, 849.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('OLED TV', 'BIG', 'TX-55LZ2000E', 12, 'AC220', '4K, 55", OLED, My Home Screen', 'Panasonic OLED LZ2000 with HCX Pro AI', 130, 1499.00);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('4K TV', 'BIG', 'TX-43MX700E', 12, 'AC220', '4K, 43", LED, Fire TV', 'Panasonic MX700 with Dolby Vision & Atmos', 70, 499.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Electric Kettle', 'SMALL', 'HD9353/90', 10, 'AC220', '1.7L, temperature control', 'Philips kettle with 5 temperature presets', 2200, 59.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Glass Kettle', 'SMALL', 'WK7475', 12, 'AC220', '1.7L, LED illumination', 'Panasonic glass kettle with cool-touch handle', 1500, 49.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Variable Temp Kettle', 'SMALL', 'KO:KE826EBK', 17, 'AC220', '1.7L, 5 temperatures', 'Dyson kettle with precise temperature control', 2200, 129.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Smart Kettle', 'SMALL', 'K55810BK', 1, 'AC220', '1.7L, Wi-Fi, app control', 'Samsung smart kettle with voice assistant', 2200, 89.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Travel Kettle', 'SMALL', 'TTM020', 19, 'AC110', '0.5L, dual voltage', 'Beko compact travel kettle 110/220V', 700, 24.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Cordless Kettle', 'SMALL', 'WK3A273', 9, 'AC220', '1.7L, limescale filter', 'Bosch CompactClass kettle with anti-drip', 2400, 44.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Stainless Steel Kettle', 'SMALL', 'SHB 6502', 21, 'AC220', '1.7L, stainless steel', 'Gorenje retro kettle with overheat protection', 2000, 39.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Quiet Kettle', 'SMALL', 'TTK110W', 15, 'AC220', '1.7L, quiet boil', 'Electrolux Expressionist kettle with quiet boil', 1850, 54.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('2-Slice Toaster', 'SMALL', 'HD2640/90', 10, 'AC220', '2 slots, 7 settings', 'Philips toaster with wide slots and crumb tray', 830, 34.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('4-Slice Toaster', 'SMALL', 'NT-2GS1', 11, 'AC220', '4 slots, 6 browning levels', 'Sony 4-slice toaster with defrost function', 1500, 49.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Long Slot Toaster', 'SMALL', 'TAT7203', 9, 'AC220', '2 long slots, 6 settings', 'Bosch long slot toaster for artisan breads', 820, 44.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Retro Toaster', 'SMALL', 'T2500', 21, 'AC220', '2 slots, retro design', 'Gorenje retro toaster with 6 browning levels', 900, 39.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Smart Toaster', 'SMALL', 'TAT8613', 15, 'AC220', '2 slots, sensor control', 'Electrolux toaster with automatic lifting', 800, 54.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('2-Slice Toaster', 'SMALL', 'TAT3A003', 9, 'AC220', '2 slots, 6 settings, eco', 'Bosch CompactClass toaster with eco mode', 800, 29.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Espresso Machine', 'SMALL', 'EP3241/54', 10, 'AC220', '15 bar, 1.8L tank, milk frother', 'Philips 3200 Series fully automatic espresso', 1500, 399.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Bean-to-Cup', 'SMALL', 'CM6360', 9, 'AC220', '15 bar, 1.6L, grinder', 'Bosch VeroAroma bean-to-cup with SensoFlow', 1600, 499.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Pod Coffee Machine', 'SMALL', 'KP1208', 15, 'AC220', '19 bar, 0.8L, Nespresso', 'Electrolux Nespresso Essenza compact pod machine', 1260, 89.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Filter Coffee Maker', 'SMALL', 'BCM8450', 9, 'AC220', '1.6L, 10 cups, thermos', 'Bosch filter coffee maker with keep-warm plate', 1000, 79.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Espresso Machine', 'SMALL', 'EC685.M', 13, 'AC220', '19 bar, 1.1L, steam wand', 'Siemens EQ.6 espresso machine with frother', 1350, 279.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Pod Machine', 'SMALL', 'HD7829/10', 10, 'AC220', '15 bar, 1L, Senseo pods', 'Philips Senseo twist with intensity selector', 1450, 119.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Drip Coffee Maker', 'SMALL', 'CM3100BK', 10, 'AC220', '1.25L, 10 cups', 'Philips drip coffee with aroma extraction', 950, 49.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('High-Speed Blender', 'SMALL', 'HR3655/00', 10, 'AC220', '1400W, 2L jug, ProBlend', 'Philips Avance blender with ProBlend technology', 1400, 129.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Stand Blender', 'SMALL', 'MBM6100', 9, 'AC220', '1200W, 1.5L, 3 speeds', 'Bosch VitaPower blender with QuattroBlade', 1200, 89.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Immersion Blender', 'SMALL', 'HR1670', 10, 'AC220', '650W, 0.6L chopper', 'Philips hand blender with ProMix technology', 650, 59.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Food Processor', 'SMALL', 'MC812842', 9, 'AC220', '1000W, 3.9L bowl, 12 functions', 'Bosch MultiTalent 8 food processor', 1000, 199.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Smoothie Blender', 'SMALL', 'ABF9S601GL', 1, 'AC220', '550W, personal blender', 'Samsung personal blender for smoothies on-the-go', 550, 69.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Mini Chopper', 'SMALL', 'HR2505', 10, 'AC220', '300W, 0.4L', 'Philips mini chopper for herbs and nuts', 300, 29.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Cordless Vacuum', 'SMALL', 'V15 Detect', 17, 'ACCUMULATOR', '25.2V, laser detection', 'Dyson V15 with laser dust detection and HEPA', 240, 699.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Robot Vacuum', 'SMALL', 'PowerBot VR7000', 1, 'ACCUMULATOR', '5W suction, 150 min, Wi-Fi', 'Samsung PowerBot with edge cleaning master', 30, 349.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Upright Vacuum', 'SMALL', 'CordZero ThinQ', 8, 'ACCUMULATOR', '200W, 80 min, A9', 'LG CordZero with self-emptying tower', 200, 799.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Canister Vacuum', 'SMALL', 'Blizzard CX1', 16, 'AC220', '890W, bagless, HEPA', 'Miele Blizzard CX1 with Vortex technology', 890, 499.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Cordless Vacuum', 'SMALL', 'SpeedPro Max', 10, 'ACCUMULATOR', '21.6V, 65 min, 5-layer filter', 'Philips SpeedPro Max with anti-tangle nozzle', 25, 349.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Robot Vacuum', 'SMALL', 'Roomba j7+', 1, 'ACCUMULATOR', '1800 Pa, auto-empty base', 'iRobot Roomba j7+ with obstacle avoidance', 26, 599.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Steam Iron', 'SMALL', 'GC4900', 10, 'AC220', '2800W, 2.4 bar steam', 'Philips PerfectCare steam iron with OptimalTEMP', 2800, 89.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Steam Station', 'SMALL', 'TDT0320GB', 9, 'AC220', '2900W, 6.5 bar, 1.2L', 'Bosch Sensixx steam generator iron', 2900, 179.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Garment Steamer', 'SMALL', 'STH7980', 13, 'AC220', '2200W, 1.5L, vertical steam', 'Siemens garment steamer with anti-calc function', 2200, 119.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Cordless Iron', 'SMALL', 'YI-903', 12, 'AC220', '2600W, 30g/min steam', 'Panasonic cordless iron with titanium soleplate', 2600, 99.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Travel Iron', 'SMALL', 'EasyTravel', 10, 'AC110', '1000W, dual voltage', 'Philips travel iron with folding handle 110/220V', 1000, 29.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Hair Dryer', 'SMALL', 'Supersonic HD08', 17, 'AC220', '1600W, intelligent heat control', 'Dyson Supersonic with intelligent heat protection', 1600, 429.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Hair Dryer', 'SMALL', 'HP8230', 10, 'AC220', '2300W, ionic, diffuser', 'Philips ThermoProtect ionic hair dryer', 2300, 59.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Hair Straightener', 'SMALL', 'GHD Platinum+', 11, 'AC220', '230°C, predictive tech', 'Sony hair straightener with ultra-zone tech', 65, 189.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Curling Iron', 'SMALL', 'HP8618', 10, 'AC220', '200°C, 25mm barrel', 'Philips StyleCare curling iron with ProCeramic', 40, 39.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Hair Dryer', 'SMALL', 'EH-NA98', 12, 'AC220', '2500W, nanoe moisture', 'Panasonic nanoe hair dryer with 3D sensing', 2500, 199.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Microwave Oven', 'SMALL', 'MW5000H', 1, 'AC220', '900W, 28L, inverter', 'Samsung microwave with Slim Fry technology', 900, 199.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Combi Microwave', 'SMALL', 'HMT84G654B', 9, 'AC220', '900W, 25L, grill', 'Bosch combi microwave with grill and hot air', 1300, 249.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Microwave Oven', 'SMALL', 'NN-E28JBM', 12, 'AC220', '800W, 20L, solo', 'Panasonic solo microwave with 800W power', 800, 99.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Over-Range Microwave', 'SMALL', 'MS30T5018AN', 1, 'AC220', '900W, 30L, convection', 'Samsung over-range microwave with ceramic inside', 900, 299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Mini Microwave', 'SMALL', 'FW177G', 10, 'AC220', '700W, 17L, compact', 'Philips compact microwave for small kitchens', 700, 89.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Air Purifier', 'SMALL', 'TP09', 17, 'AC220', 'HEPA H13, 290m3/h, Wi-Fi', 'Dyson Purifier Hot+Cool with formaldehyde filter', 56, 699.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Air Purifier', 'SMALL', 'AC3858/50', 10, 'AC220', 'HEPA, 400m3/h, NanoProtect', 'Philips 3000i Series with air quality sensor', 61, 349.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Tower Fan', 'SMALL', 'AM07', 17, 'AC220', '10 speeds, sleep timer, remote', 'Dyson Cool tower fan with Air Multiplier', 40, 449.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Desk Fan', 'SMALL', 'TDC 35 E', 19, 'AC220', '35W, 3 speeds, oscillating', 'Beko desk fan with 3 speed settings', 35, 29.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Air Fryer', 'SMALL', 'HD9270/90', 10, 'AC220', '1425W, 6.2L, Rapid Air', 'Philips XXL air fryer with FatRemoval filter', 1425, 199.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Air Fryer Oven', 'SMALL', 'EAF9G', 15, 'AC220', '1800W, 9L, 9 presets', 'Electrolux air fryer oven with rotisserie', 1800, 149.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Electric Grill', 'SMALL', 'TFB3302', 9, 'AC220', '2000W, 0.38m2, non-stick', 'Bosch contact grill with floating hinge', 2000, 89.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Rice Cooker', 'SMALL', 'SR-CNX187', 12, 'AC220', '1000W, 1.8L, 10 cups', 'Panasonic rice cooker with fuzzy logic', 1000, 149.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Slow Cooker', 'SMALL', 'HP5510', 10, 'AC220', '140W, 4.5L, 2 settings', 'Philips all-in-one cooker with keep warm', 140, 59.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Sandwich Maker', 'SMALL', 'ST3A', 19, 'AC220', '700W, non-stick plates', 'Beko sandwich and waffle maker with indicator', 700, 24.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Stand Mixer', 'SMALL', 'MUM9BX5S25', 9, 'AC220', '1500W, 5.5L bowl, 14 speeds', 'Bosch OptiMUM stand mixer with scale sensor', 1500, 499.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Bread Maker', 'SMALL', 'SD-ZX2522', 12, 'AC220', '680W, 1.5kg, 33 programs', 'Panasonic bread maker with yeast and nut dispenser', 680, 249.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Juicer', 'SMALL', 'HR1922/20', 10, 'AC220', '1200W, 1.5L, filter', 'Philips Viva Collection juicer with QuickClean', 1200, 69.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Electric Shaver', 'SMALL', 'S9987/55', 10, 'AC110', '50W, wet&dry, 4D flex head', 'Philips Series 9000 rotary shaver with SkinIQ', 15, 299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Induction Hob', 'SMALL', 'NZ64T37066K', 1, 'AC220', '7200W, 4 zones, 17 power levels', 'Samsung 4-zone induction hob with FlexZone', 7200, 499.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Portable Induction', 'SMALL', 'TI9573X4G', 9, 'AC220', '3600W, 2 zones, DirectSelect', 'Bosch portable double induction hob', 3600, 299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Waffle Maker', 'SMALL', 'WB3450BR', 9, 'AC220', '1000W, 4 waffles, removable plates', 'Bosch waffle maker with temperature indicator', 1000, 49.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Electric Grill', 'SMALL', 'HC 403 D', 21, 'AC220', '2000W, 35x25cm, non-stick', 'Gorenje contact grill with floating lid', 2000, 59.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Wireless Charger', 'SMALL', 'EP-P5400', 1, 'AC220', '15W, dual pad, fast charge', 'Samsung Duo wireless charger for phone and watch', 15, 49.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Dehumidifier', 'SMALL', 'HD35', 8, 'AC220', '350W, 10L/day, 20m2', 'LG dehumidifier with auto-restart', 350, 199.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Humidifier', 'SMALL', 'HU4803/01', 10, 'AC220', '32W, 2L, ultrasonic', 'Philips ultrasonic humidifier with auto-humidity', 32, 79.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Clothes Steamer', 'SMALL', 'DR8020', 17, 'ACCUMULATOR', '30W, fabric care', 'Dyson cordless clothes steamer with allergen reduction', 30, 299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Portable Blender', 'SMALL', 'MX-ZM181', 12, 'ACCUMULATOR', '150W, 350ml, USB-C charge', 'Panasonic portable blender for smoothies', 150, 49.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Smart Speaker', 'SMALL', 'HW-Q990B', 1, 'AC220', '656W, 11.1.4 ch, Dolby Atmos', 'Samsung Q-series soundbar with Rear speakers', 656, 1299.99);
INSERT INTO appliance (name, category, model, manufacturer_id, power_type, characteristic, description, power, price) VALUES ('Soundbar', 'SMALL', 'HT-A7000', 11, 'AC220', '500W, 7.1.2 ch, Dolby Atmos', 'Sony 7.1.2ch soundbar with built-in subwoofer', 500, 999.99);

-- Orders
INSERT INTO orders (approved, client_id, employee_id) VALUES (true,  1, 1);
INSERT INTO orders (approved, client_id, employee_id) VALUES (true,  2, 2);
INSERT INTO orders (approved, client_id, employee_id) VALUES (true,  5, 1);
INSERT INTO orders (approved, client_id, employee_id) VALUES (null,  3, null);
INSERT INTO orders (approved, client_id, employee_id) VALUES (null,  4, null);
INSERT INTO orders (approved, client_id, employee_id) VALUES (null,  8, null);
INSERT INTO orders (approved, client_id, employee_id) VALUES (false, 6, null);
INSERT INTO orders (approved, client_id, employee_id) VALUES (false, 7, null);

-- Order rows
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (1, 8,  1299.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (1, 18,  699.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (1, 27,  649.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (2, 46, 1299.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (2, 64,  399.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (2, 77,  699.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (3, 35,  799.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (3, 40,  799.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (3, 50,   59.99, 2);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (3, 58,   34.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (4, 19,  749.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (4, 29, 1399.00, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (4, 38,  899.00, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (5, 47,  849.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (5, 65,  499.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (5, 71,  129.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (5, 74,  199.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (6, 9,  1099.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (6, 78,  349.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (6, 83,   89.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (7, 77,  699.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (7, 80,  499.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (8, 68,  279.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (8, 52,  129.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (8, 61,   39.99, 1);
INSERT INTO order_row (order_id, appliance_id, amount, number) VALUES (8, 66,   89.99, 3);