UPDATE manufacturer SET country = 'South Korea',   founded_year = 1938 WHERE name = 'Samsung';
UPDATE manufacturer SET country = 'USA',           founded_year = 1984 WHERE name = 'Dell';
UPDATE manufacturer SET country = 'USA',           founded_year = 1939 WHERE name = 'HP';
UPDATE manufacturer SET country = 'USA',           founded_year = 1976 WHERE name = 'Apple';
UPDATE manufacturer SET country = 'China',         founded_year = 1984 WHERE name = 'Lenovo';
UPDATE manufacturer SET country = 'Taiwan',        founded_year = 1976 WHERE name = 'Acer';
UPDATE manufacturer SET country = 'USA',           founded_year = 1969 WHERE name = 'AMD';
UPDATE manufacturer SET country = 'South Korea',   founded_year = 1958 WHERE name = 'LG';
UPDATE manufacturer SET country = 'Germany',       founded_year = 1886 WHERE name = 'Bosch';
UPDATE manufacturer SET country = 'Netherlands',   founded_year = 1891 WHERE name = 'Philips';
UPDATE manufacturer SET country = 'Japan',         founded_year = 1946 WHERE name = 'Sony';
UPDATE manufacturer SET country = 'Japan',         founded_year = 1918 WHERE name = 'Panasonic';
UPDATE manufacturer SET country = 'Germany',       founded_year = 1847 WHERE name = 'Siemens';
UPDATE manufacturer SET country = 'USA',           founded_year = 1911 WHERE name = 'Whirlpool';
UPDATE manufacturer SET country = 'Sweden',        founded_year = 1919 WHERE name = 'Electrolux';
UPDATE manufacturer SET country = 'Germany',       founded_year = 1899 WHERE name = 'Miele';
UPDATE manufacturer SET country = 'United Kingdom',founded_year = 1991 WHERE name = 'Dyson';
UPDATE manufacturer SET country = 'China',         founded_year = 1984 WHERE name = 'Haier';
UPDATE manufacturer SET country = 'Turkey',        founded_year = 1955 WHERE name = 'Beko';
UPDATE manufacturer SET country = 'Italy',         founded_year = 1975 WHERE name = 'Indesit';
UPDATE manufacturer SET country = 'Slovenia',      founded_year = 1950 WHERE name = 'Gorenje';